server:
  port: 8080

spring:
  datasource:
    username: root
    password: ok
    url: jdbc:mysql://localhost:3306/smbms?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false
#  redis:
#    host: localhost
#    port: 6379
#    database: 0

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zb.sbm.entity
  configuration:
    auto-mapping-behavior: full


logging:
  level:
    com:
      zb:
        sbm:
          dao: debug
